# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactiveExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveExample
    pod 'ReactiveObjC'
    pod 'Masonry'
    pod 'AFNetworking'

  target 'ReactiveExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveExampleUITests' do
    # Pods for testing
  end

end
